# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1saPA0lVq_iNs6EQ_MsQF0tt8KcZbNRWA
"""



def first(s):
  freq={}
  for char in s:
    freq[char]=freq.get(char,0)+1
    for char in s:
      if freq[char]==1:
        return char
        return none
s=input("enter a sting:")
result=first(s)
print("first non-repeating charcter:",result if result else "none found")