# -*- coding: utf-8 -*-
"""Untitled13.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YvRh7SZRv7wUeIIGLKKYb0SJtlyzu0OW
"""

rows = int(input("Enter the row size for the pattern: "))
for i in range(1, rows + 1):
    for j in range(1, i + 1):
        print("*", end=" ")
    print()