# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CWXYN-2vU1UJs1VF-Si9OV8e3D9uFX2y
"""

rows = 5
for i in range(1, rows + 1):
    print('*' * i)