# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1m79zBH8l5xpoZkVq6TXS2L3fTcN3L1L4
"""

t = 1
last_index = -1
a = [10, 20, 30, 20, 40]
tar = 20

for i in range(len(a)):
    if a[i] == tar:
        last_index = i

if last_index != -1:
    print("Last index:", last_index)
else:
    print("Target not found")