# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1naXQfLqD-CHrzZono_QYph3gEsnCBwut
"""

for counter in range(1, 6):
    print('number:', counter)
    if counter < 5:
        print('still counting!')
    else:
        print('finished!')