# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1-3TrOKzEWGj7MgIHmoZ-wu0v7aZPCxmR
"""



a=5
b=6
c=7
a=float(input('enter first side: '))
b=float(input('enter first side: '))
c=float(input('enter first side: '))
s=(a+b+c)/2
area=(s*(s-a)*(s-b)*(s-c))**0.5
print('the area of the triangle is %0.2f' %area)