# -*- coding: utf-8 -*-
"""Untitled11.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1h7BNovRmr--X1efrl1lDARPqU3wUo7nG
"""

my_list = [64, 34, 25, 12, 22, 11, 5, 90]
n = len(my_list)

for i in range(n - 1):
    for j in range(n - i - 1):
        if my_list[j] > my_list[j + 1]:
            my_list[j], my_list[j + 1] = my_list[j + 1], my_list[j]
    print(my_list)